name: sber_pay
description: SberPay Plugin for Flutter.
version: 0.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: plugin.sdk.sber_pay
        pluginClass: SberPayPlugin
      ios:
        pluginClass: SberPayPlugin

  assets:
    - assets/sberpay_logo.png

  fonts:
    - family: SberPaySans
      fonts:
        - asset: assets/fonts/spay_sans_text.ttf