name: sber_pay_example
description: Demonstrates how to use the sber_pay plugin.
version: 1.2.0
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sber_pay:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
