name: sber_pay_android
description: Android implementation of the sber_pay plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: sber_pay
    platforms:
      android:
        package: plugin.sdk
        pluginClass: SberPayPlugin
        dartPluginClass: SberPayAndroid

dependencies:
  flutter:
    sdk: flutter
  sber_pay_platform_interface:
    path: ../sber_pay_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
